version: '3.8'

services:
  web:
    image: yourusername/papermind:latest
    ports:
      - "80:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./vector_db:/app/vector_db
    restart: unless-stopped
    environment:
      - PORT=5000
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G 